# Netlify Configuration for Next.js
[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  # Node version
  NODE_VERSION = "18"
  # Next.js build settings
  NEXT_TELEMETRY_DISABLED = "1"

# Redirect rules for Next.js
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Essential files plugin for Next.js
[plugins]
  [[plugins.package]]
    package = "@netlify/plugin-nextjs"

